#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 25 22:59:11 ORAT 2026
allowUnknownShaders=false
colorSpace=REC2020
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.9.3 + EuphoriaPatches_1.10.5
