#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Aug 19 22:47:51 ORAT 2026
allowUnknownShaders=false
colorSpace=REC2020
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.8.1 + EuphoriaPatches_1.9.3
